@host = http://127.0.0.1:8080/nepaBackend/

@jwt = eyJhbGciOiJIUzUxMiJ9.dGVzdF9rZXlfb25seQ.b1J2BbcMkZ5y6dkTAxTHMU0HrxXbVfeaGEyFz-MX3_p-7R27HSLctwfVk_qLsBnB2ewa6c6py46JC3UGibhN1w 
GET {{host}}user/exists HTTP/1.1
SECRET: TEST_ONLY
APP_KEY: test_key_only
Authorization: Bearer {{jwt}}
//Jwt-Token: {{jwt}}
Content-Type: application/json
### 